@BankRUs.Api_HostAddress = https://localhost:8000

### Öppna konto
POST https://localhost:8000/api/accounts
Content-Type: application/json
{
  "firstName": "Bolly",
  "lastName": "Doe",
  "socialSecurityNumber": "189002039817",
  "email": "bolly@doe.com"
}


### Öppna bankkonto
POST https://localhost:8000/api/bank-accounts
Content-Type: application/json
{
  "userId": "4882a05f-4406-4f9c-9647-4c1bf901bff8",
  "name": "Semesterkonto"
}

### Transaction
POST https://localhost:8000/api/bank-accounts/567e715d-58b2-4f20-a41e-1b41c65cbbe2/deposits
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODgyYTA1Zi00NDA2LTRmOWMtOTY0Ny00YzFiZjkwMWJmZjgiLCJlbWFpbCI6ImJvbGx5QGRvZS5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJib2xseUBkb2UuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3NzA4ODc3NzgsImlzcyI6IkJhbmtSVXMuQXBpIiwiYXVkIjoiQmFua1JVcy5DbGllbnQifQ.UgAAkNyHcjfNnFdysjooDiKBeA5lTimIB6aikGZVTGg

{
  "amount": 250.00,
  "reference": "Lön januari"
}
### Withdrawals
POST https://localhost:8000/api/bank-accounts/567e715d-58b2-4f20-a41e-1b41c65cbbe2/withdrawals
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0ODgyYTA1Zi00NDA2LTRmOWMtOTY0Ny00YzFiZjkwMWJmZjgiLCJlbWFpbCI6ImJvbGx5QGRvZS5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJib2xseUBkb2UuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXIiLCJleHAiOjE3NzA4ODc3NzgsImlzcyI6IkJhbmtSVXMuQXBpIiwiYXVkIjoiQmFua1JVcy5DbGllbnQifQ.UgAAkNyHcjfNnFdysjooDiKBeA5lTimIB6aikGZVTGg

{
  "amount": 90.00,
  "reference": "Uttag bankomat"
}


### Hämta alla konton för en användare
GET https://localhost:8000/api/accounts/4882a05f-4406-4f9c-9647-4c1bf901bff8

### Logga in / Autentisera
POST https://localhost:8000/api/auth/login
Content-Type: application/json
{
  "username": "bolly@doe.com",
  "password": "Secret#1"
}


### Hämta kontouppgifter
GET https://localhost:8000/api/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTQyZGNmNy00OTRjLTRiYWItOGQ5NC0yMWY5NWE0MGQzNDYiLCJlbWFpbCI6InBvbGx5LnVwZGF0ZWRAZG9lLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6InBvbGx5LnVwZGF0ZWRAZG9lLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzcwMjg0NzE3LCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.x2cRN5TsZA_G34_thtEZK3OK_Rx0vxtjFxMBQzBKkRA



### Login as CustomerService
POST https://localhost:8000/api/auth/login
Content-Type: application/json
{
  "username": "service@test.com",
  "password": "Secret#1"
}


### Get customers
GET https://localhost:8000/api/customers?page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQ4MWM2OS0yMGJmLTQ1MGYtOTNiNC1lZTEzYWU1MjU0MmUiLCJlbWFpbCI6InNlcnZpY2VAdGVzdC5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXJTZXJ2aWNlIiwiZXhwIjoxNzcwMTMyNjQ1LCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.GdTIkLaTVG-4OR5-AD3WQtCcNcU0DElggPuPyCNY7HM

### Get customer by id
GET https://localhost:8000/api/customers/0142dcf7-494c-4bab-8d94-21f95a40d346
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQ4MWM2OS0yMGJmLTQ1MGYtOTNiNC1lZTEzYWU1MjU0MmUiLCJlbWFpbCI6InNlcnZpY2VAdGVzdC5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXJTZXJ2aWNlIiwiZXhwIjoxNzcwMTIzMTkwLCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.f1t56hQxBWMrMs5ymfBoDylord-5r7CoNB0WMK7_9uQ


### Search customers by SSN
GET https://localhost:8000/api/customers?ssn=19010101&page=1&pageSize=10
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQ4MWM2OS0yMGJmLTQ1MGYtOTNiNC1lZTEzYWU1MjU0MmUiLCJlbWFpbCI6InNlcnZpY2VAdGVzdC5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXJTZXJ2aWNlIiwiZXhwIjoxNzcwMTMwMTE0LCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.hHdDU73oRsFRkF-5pej0vuhfUCvr3SaVeaVywRJs0hk


### Login as Customer
POST https://localhost:8000/api/auth/login
Content-Type: application/json

{
  "username": "polly.updated@doe.com",
  "password": "Secret#1"
}

### Update my account details
PATCH https://localhost:8000/api/me
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTQyZGNmNy00OTRjLTRiYWItOGQ5NC0yMWY5NWE0MGQzNDYiLCJlbWFpbCI6InBvbGx5LnVwZGF0ZWRAZG9lLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6InBvbGx5LnVwZGF0ZWRAZG9lLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzcwMjg0NzE3LCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.x2cRN5TsZA_G34_thtEZK3OK_Rx0vxtjFxMBQzBKkRA

{
  "firstName": "PollyUpdated",
  "lastName": "DoeUpdated",
  "email": "polly.updated@doe.com",
  "socialSecurityNumber": "189001079999"
}

### Delete my account
DELETE https://localhost:8000/api/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTQyZGNmNy00OTRjLTRiYWItOGQ5NC0yMWY5NWE0MGQzNDYiLCJlbWFpbCI6InBvbGx5LnVwZGF0ZWRAZG9lLmNvbSIsInByZWZlcnJlZF91c2VybmFtZSI6InBvbGx5LnVwZGF0ZWRAZG9lLmNvbSIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkN1c3RvbWVyIiwiZXhwIjoxNzcwMjg4NDI2LCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.VdZsXgwvtSAx7cbKlNvnTgeqpZKEMBd0-cKDzU8cg1o

### Delete customer by id
DELETE https://localhost:8000/api/customers/abae0a63-bdef-458a-8655-188ad297f850
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJhZmQ4MWM2OS0yMGJmLTQ1MGYtOTNiNC1lZTEzYWU1MjU0MmUiLCJlbWFpbCI6InNlcnZpY2VAdGVzdC5jb20iLCJwcmVmZXJyZWRfdXNlcm5hbWUiOiJzZXJ2aWNlQHRlc3QuY29tIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQ3VzdG9tZXJTZXJ2aWNlIiwiZXhwIjoxNzcwMjg4OTU4LCJpc3MiOiJCYW5rUlVzLkFwaSIsImF1ZCI6IkJhbmtSVXMuQ2xpZW50In0.Yg9KO-SPs7ieNRp6etG9Y_-LYeEH3xL1tan992Obf2k
