@BankRUs.Api_HostAddress = https://localhost:8000

### Öppna konto

POST https://localhost:8000/api/accounts
Content-Type: application/json

{
  "firstName": "Kelly",
  "lastName": "Doe",
  "socialSecurityNumber": "19910321-7205",
  "email": "kelly@doe.com"
}

### Öppna bankkonto
POST https://localhost:8000/api/bank-accounts
Content-Type: application/json

{
  "userId": "2c7cc717-5dbe-4db3-a91f-6f40f91e2bff"
}


### Hämta alla konton för en användare

GET https://localhost:8000/api/accounts/2c7cc717-5dbe-4db3-a91f-6f40f91e2bff

