@BankRUs.Api_HostAddress = https://localhost:8000

### Öppna konto

POST https://localhost:8000/api/accounts
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "socialSecurityNumber": "19820621-1578",
  "email": "john@doe.com"
}


